const actionsTypes = {
  FETCH_IMAGE_URL_SUCCESS: 'FETCH_IMAGE_URL_SUCCESS',
  FETCH_IMAGE_URL_FAILURE: 'FETCH_IMAGE_URL_FAILURE',
  FETCH_IMAGE_URL_REQUEST: 'FETCH_IMAGE_URL_REQUEST',
};

export default actionsTypes;
