const actionsTypes = {
  FETCH_IMAGE_URL_SUCCESS: 'FETCH_IMAGE_URL_SUCCESS',
  FETCH_IMAGE_URL_FAILURE: 'FETCH_IMAGE_URL_FAILURE',
  FETCH_IMAGE_URL_REQUEST: 'FETCH_IMAGE_URL_REQUEST',
  FETCH_POPULAR_MOVIES_SUCCESS: 'FETCH_POPULAR_MOVIES_SUCCESS',
  FETCH_POPULAR_MOVIES_FAILURE: 'FETCH_POPULAR_MOVIES_FAILURE',
  FETCH_POPULAR_MOVIES_REQUEST: 'FETCH_POPULAR_MOVIES_REQUEST',
};

export default actionsTypes;
